import * as vscode from 'vscode';
import { collectGlobPatterns, findCandidateFiles, matchesConfiguredLanguage } from './languageIndex';
import { findEntryAtOffset, parseSource } from './plsqlParser';
import { PerKeyDebouncer } from './perKeyDebouncer';
import { SourceLocationIndex } from './sourceLocationIndex';

/** onDidChangeTextDocument/FileSystemWatcher's onDidChange fire once per keystroke/write burst; this is how long we wait for one to settle before re-parsing. */
const REINDEX_DEBOUNCE_MS = 400;

export interface SourceLocation {
    uri: vscode.Uri;
    range: vscode.Range;
    isBody: boolean;
}

/**
 * PACKAGE[.PROCEDURE] -> location, built from the workspace's PL/SQL files
 * (matched by language id, see languageIndex.ts). The owner is not part of
 * the key — it isn't reliably present in source files and comes from the
 * active connection profile instead.
 *
 * The map itself (add/remove/lookup, including the body-over-spec
 * preference) lives in SourceLocationIndex, and per-URI debouncing lives in
 * PerKeyDebouncer — both vscode-free so they are unit-testable outside the
 * extension host (see their own doc comments). This class is the
 * vscode-facing glue on top: turning TextDocument/Uri/FileSystemWatcher
 * events into calls on those two, and turning lookup() results back into
 * real vscode.Range/vscode.Position instances.
 */
export class SourceIndex implements vscode.Disposable {
    private readonly locationIndex = new SourceLocationIndex<vscode.Uri>();
    private readonly reindexDebouncer = new PerKeyDebouncer(REINDEX_DEBOUNCE_MS);
    private readonly disposables: vscode.Disposable[] = [];
    private watchers: vscode.Disposable[] = [];
    private buildFullIndexPromise: Promise<void> | undefined;

    constructor() {
        this.disposables.push(
            vscode.workspace.onDidOpenTextDocument((doc) => this.indexDocument(doc)),
            vscode.workspace.onDidChangeTextDocument((e) => this.scheduleReindex(e.document)),
            vscode.workspace.onDidCloseTextDocument((doc) => this.onDocumentClosed(doc)),
            vscode.workspace.onDidChangeConfiguration((e) => this.onConfigurationChanged(e))
        );
    }

    /**
     * files.associations changes which on-disk files even become candidates
     * (see collectGlobPatterns()), and utplsql.discovery.languageIds changes
     * which language ids count — either one can turn a file that used to be
     * invisible to lookupPackage() into a match (or vice versa), so a full
     * rescan is needed rather than just re-parsing already-known files. The
     * FileSystemWatchers created below are built from the same two
     * settings, so they go stale in exactly the same situations and must be
     * rebuilt alongside the index rather than only once at activation.
     */
    private onConfigurationChanged(e: vscode.ConfigurationChangeEvent): void {
        if (e.affectsConfiguration('files.associations') || e.affectsConfiguration('utplsql.discovery.languageIds')) {
            void this.buildFullIndex();
        }
    }

    dispose(): void {
        this.disposables.forEach((d) => d.dispose());
        this.disposeWatchers();
        this.reindexDebouncer.dispose();
    }

    private disposeWatchers(): void {
        this.watchers.forEach((w) => w.dispose());
        this.watchers = [];
    }

    /**
     * One FileSystemWatcher per glob pattern collectGlobPatterns() returns,
     * so PL/SQL sources changed outside the editor — a git checkout/pull, a
     * branch switch, a file generated by another tool — are noticed instead
     * of silently going stale for the rest of the session (#26). Recreated
     * on every buildFullIndex() call (activation, and every configuration
     * change that already triggers one) rather than created once in the
     * constructor, since the pattern set itself depends on
     * files.associations/utplsql.discovery.languageIds plus whichever
     * extensions are installed, all of which buildFullIndex() is already
     * reacting to.
     *
     * files.watcherExclude still applies to these — there is no API to opt
     * a watcher out of it — so a file under an excluded folder stays
     * invisible to both this and buildFullIndex()'s own findCandidateFiles()
     * call. That is exactly why buildFullIndex() remains the activation-time
     * backstop instead of being replaced by watchers entirely: it is the
     * only path that would ever notice such a file (if the user reloads).
     */
    private recreateWatchers(): void {
        this.disposeWatchers();
        this.watchers = collectGlobPatterns().map((pattern) => {
            const watcher = vscode.workspace.createFileSystemWatcher(pattern);
            watcher.onDidCreate((uri) => void this.indexFile(uri));
            watcher.onDidChange((uri) => this.scheduleReindexUri(uri));
            watcher.onDidDelete((uri) => this.removeUri(uri));
            return watcher;
        });
    }

    /**
     * Debounced the same way scheduleReindex() below debounces editor
     * edits, and against the *same* PerKeyDebouncer keyed on uri.toString():
     * saving an open document fires both an onDidChangeTextDocument
     * (already scheduled against the in-memory buffer) and this
     * FileSystemWatcher's onDidChange for the same file within the same
     * window. Sharing one timer per key means whichever of the two was
     * scheduled last is what actually runs — by the time it fires the
     * buffer and disk agree anyway, so there is nothing to reconcile and no
     * separate bookkeeping needed to avoid indexing the same save twice.
     */
    private scheduleReindexUri(uri: vscode.Uri): void {
        this.reindexDebouncer.schedule(uri.toString(), () => void this.indexFile(uri));
    }

    private scheduleReindex(doc: vscode.TextDocument): void {
        if (!matchesConfiguredLanguage(doc)) {
            return;
        }
        this.reindexDebouncer.schedule(doc.uri.toString(), () => this.indexDocument(doc));
    }

    /**
     * onDidChangeTextDocument only fires while a document stays open, so a
     * debounced re-index scheduled against the live editor buffer
     * (scheduleReindex) is only ever right up until the document closes.
     * For an untitled/unsaved document, closing it destroys the only copy
     * of its content that ever existed, so its entries must go too —
     * otherwise lookupPackage() keeps handing out a vscode.Uri that reopens
     * as an empty untitled tab. For a document backed by a real file, the
     * file itself still exists, so re-reading it from disk is what's
     * needed instead of leaving whatever indexDocument() last saw in place:
     * the editor can be closed with unsaved changes discarded, or after an
     * external revert, and either way the in-memory buffer indexDocument()
     * indexed no longer matches anything once that buffer is gone.
     *
     * Cancels any still-pending debounced reindex for this uri first — left
     * pending, it would fire later with a TextDocument reference that is
     * already stale by the time this method's own removeUri()/indexFile()
     * call has already brought the index up to date.
     */
    private onDocumentClosed(doc: vscode.TextDocument): void {
        this.reindexDebouncer.cancel(doc.uri.toString());
        if (doc.isUntitled) {
            this.removeUri(doc.uri);
            return;
        }
        void this.indexFile(doc.uri);
    }

    private removeUri(uri: vscode.Uri): void {
        this.locationIndex.removeOwner(uri.toString());
    }

    private addEntries(uri: vscode.Uri, text: string): void {
        this.locationIndex.setOwnerEntries(uri.toString(), uri, parseSource(text));
    }

    indexDocument(doc: vscode.TextDocument): void {
        if (!matchesConfiguredLanguage(doc)) {
            return;
        }
        this.addEntries(doc.uri, doc.getText());
    }

    /** Reads uri fresh from disk and re-indexes it. Used for the initial scan, watcher create/change events, and re-reading a just-closed saved document. */
    async indexFile(uri: vscode.Uri): Promise<void> {
        try {
            const bytes = await vscode.workspace.fs.readFile(uri);
            this.addEntries(uri, Buffer.from(bytes).toString('utf8'));
        } catch {
            // The file may have disappeared between whatever queued this call
            // (findCandidateFiles's scan, a debounced watcher event, a closed
            // document's re-read) and this readFile actually running — nothing
            // to index, and removeUri()/a future onDidDelete already covers
            // the "it's really gone" case.
        }
    }

    /**
     * Single-flighted: onConfigurationChanged can trigger this more than
     * once in a burst (e.g. a settings.json edit touching both
     * files.associations and utplsql.discovery.languageIds fires one
     * onDidChangeConfiguration each, both matched by the same `if` above),
     * and two overlapping calls both clearing and repopulating
     * locationIndex would interleave their writes into a half-cleared
     * index — whichever call's clear() happened to run last would wipe out
     * entries the other call had already re-added. A caller that arrives
     * while a build is already in flight gets that same in-flight build's
     * result instead of starting a second, overlapping one.
     */
    async buildFullIndex(): Promise<void> {
        if (!this.buildFullIndexPromise) {
            this.buildFullIndexPromise = this.doBuildFullIndex().finally(() => {
                this.buildFullIndexPromise = undefined;
            });
        }
        return this.buildFullIndexPromise;
    }

    private async doBuildFullIndex(): Promise<void> {
        this.recreateWatchers();
        this.locationIndex.clear();
        const files = await findCandidateFiles();
        await Promise.all(files.map((uri) => this.indexFile(uri)));
    }

    /** Prefer a package body over a spec, since that's where TestMessages should point. */
    lookup(key: string): SourceLocation | undefined {
        const found = this.locationIndex.lookup(key);
        if (!found) {
            return undefined;
        }
        return {
            uri: found.owner,
            isBody: found.isBody,
            range: new vscode.Range(
                new vscode.Position(found.start.line, found.start.character),
                new vscode.Position(found.end.line, found.end.character)
            )
        };
    }

    lookupPackage(pkg: string): SourceLocation | undefined {
        return this.lookup(pkg);
    }

    lookupProcedure(pkg: string, proc: string): SourceLocation | undefined {
        return this.lookup(`${pkg}.${proc}`) ?? this.lookup(pkg);
    }

    /** utplsql.runTestAtCursor: PACKAGE or PACKAGE.PROCEDURE declared at/above the cursor. */
    getPathAtCursor(doc: vscode.TextDocument, position: vscode.Position): string | undefined {
        const entries = parseSource(doc.getText());
        const offset = doc.offsetAt(position);
        return findEntryAtOffset(entries, offset)?.key;
    }
}
