-- Performance fixture generator for the utPLSQL Test Explorer tree view.
--
-- Generates UT_PERF_TEST_0001 .. UT_PERF_TEST_<p_packages> test packages,
-- each with p_tests_min..p_tests_max test procedures (~15,000 procedures at
-- the default 1000 packages), covering:
--   - outcome: ~75% pass, ~10% fail, ~5% raise an unhandled exception,
--     ~10% --%disabled (see ut_perf_gen.generate's OUTCOME buckets below)
--   - duration: ~10% of ALL generated tests sleep 2-10s ("slow" tier, as
--     requested), ~10% sleep a short fixed amount ("medium" tier, for a
--     broader spread of durations in the tree view), ~80% run instantly
--   - tree shape: ~40% of packages carry --%suitepath(perf.gNN) (20
--     groups), and ~20% additionally nest their last test under
--     --%context(nested) -- both exercise buildSchemaTree()'s
--     parent-lookup-by-path logic (src/testing/controller.ts) at depth.
--
-- Outcome and duration are two INDEPENDENT axes (a slow test can also fail,
-- an error test can also be disabled-and-never-run, etc.) — each is its own
-- ORA_HASH() draw over the deterministic (package, test-number, p_seed)
-- key, so the same p_seed always reproduces the same tree.
--
-- sleep_scale lives in ut_perf_config, read at RUN TIME by the generated
-- test bodies via ut_perf_gen.scale() — so the "slow"/"medium" sleep
-- durations for all ~15,000 already-compiled procedures can be dialed up or
-- down (0 = instant, for measuring tree/discovery cost in isolation; 1 =
-- full 2-10s tests) without regenerating anything. See
-- test/perf/support/perfFixture.ts and docs/performance.md for the three
-- run modes this enables.

CREATE TABLE ut_perf_config (
    sleep_scale         NUMBER DEFAULT 0 NOT NULL,
    packages_generated  NUMBER,
    seed                NUMBER,
    generated_at        TIMESTAMP
)
/

CREATE OR REPLACE PACKAGE ut_perf_gen IS

    /** Current sleep_scale multiplier, read by every generated test body. Defaults to 0 (instant) if ut_perf_config is empty. */
    FUNCTION scale RETURN NUMBER;

    /** Sets sleep_scale without touching any already-generated package -- see the file header. */
    PROCEDURE set_sleep_scale(p_scale NUMBER);

    /**
     * (Re)generates p_packages test packages named UT_PERF_TEST_0001..NNNN,
     * each with a deterministic (p_seed) number of tests in
     * [p_tests_min, p_tests_max] and a deterministic mix of outcomes and
     * durations. Safe to call again with a different p_packages: it only
     * ever adds/replaces UT_PERF_TEST_*, never drops extra ones from a
     * previous larger run -- call drop_all() first for a clean slate.
     * Raises an error listing any package left INVALID by a generation bug
     * rather than leaving a silently broken fixture behind.
     */
    PROCEDURE generate(
        p_packages  NUMBER DEFAULT 1000,
        p_tests_min NUMBER DEFAULT 10,
        p_tests_max NUMBER DEFAULT 20,
        p_seed      NUMBER DEFAULT 42
    );

    /** Drops every UT_PERF_TEST_* package (spec + body) generated by generate(). */
    PROCEDURE drop_all;

END ut_perf_gen;
/
CREATE OR REPLACE PACKAGE BODY ut_perf_gen IS

    /**
     * ORA_HASH is a SQL-only built-in -- PL/SQL has no native declaration
     * for it (PLS-00201, confirmed against a live Oracle 23ai instance), so
     * every call has to be routed through the SQL engine via SELECT INTO
     * rather than used directly as a PL/SQL expression.
     */
    FUNCTION hash_bucket(p_value VARCHAR2, p_bucket PLS_INTEGER, p_seed NUMBER) RETURN PLS_INTEGER IS
        l_result PLS_INTEGER;
    BEGIN
        SELECT ORA_HASH(p_value, p_bucket, p_seed) INTO l_result FROM dual;
        RETURN l_result;
    END hash_bucket;

    FUNCTION scale RETURN NUMBER IS
        l_scale ut_perf_config.sleep_scale%TYPE;
    BEGIN
        SELECT sleep_scale INTO l_scale FROM ut_perf_config WHERE ROWNUM = 1;
        RETURN l_scale;
    EXCEPTION
        WHEN NO_DATA_FOUND THEN
            RETURN 0;
    END scale;

    PROCEDURE set_sleep_scale(p_scale NUMBER) IS
    BEGIN
        UPDATE ut_perf_config SET sleep_scale = p_scale;
        IF SQL%ROWCOUNT = 0 THEN
            INSERT INTO ut_perf_config (sleep_scale) VALUES (p_scale);
        END IF;
        COMMIT;
    END set_sleep_scale;

    PROCEDURE generate(
        p_packages  NUMBER DEFAULT 1000,
        p_tests_min NUMBER DEFAULT 10,
        p_tests_max NUMBER DEFAULT 20,
        p_seed      NUMBER DEFAULT 42
    ) IS
        l_pkg_name     VARCHAR2(30);
        l_num_tests    PLS_INTEGER;
        l_spec         VARCHAR2(32000);
        l_body         VARCHAR2(32000);
        l_key          VARCHAR2(200);
        l_test_name    VARCHAR2(30);
        l_outcome      PLS_INTEGER;
        l_duration     PLS_INTEGER;
        l_slow_secs    PLS_INTEGER;
        l_med_secs     NUMBER;
        l_disabled     BOOLEAN;
        l_is_suitepath BOOLEAN;
        l_is_context   BOOLEAN;
        l_group_no     PLS_INTEGER;
        l_invalid_cnt  PLS_INTEGER;
    BEGIN
        FOR pkg_no IN 1 .. p_packages LOOP
            l_pkg_name := 'UT_PERF_TEST_' || LPAD(pkg_no, 4, '0');
            l_num_tests := p_tests_min +
                MOD(hash_bucket(l_pkg_name || '.n', 999999, p_seed), GREATEST(p_tests_max - p_tests_min + 1, 1));
            l_is_suitepath := MOD(pkg_no, 5) < 2;                      -- ~40% of packages
            l_is_context   := MOD(pkg_no, 5) = 0 AND l_num_tests >= 2; -- ~20% of packages
            l_group_no     := MOD(pkg_no, 20);                        -- 20 suitepath groups

            l_spec := 'CREATE OR REPLACE PACKAGE ' || l_pkg_name || ' IS' || CHR(10)
                    || '  --%suite(Performance fixture package ' || TO_CHAR(pkg_no) || ')' || CHR(10);
            IF l_is_suitepath THEN
                l_spec := l_spec || '  --%suitepath(perf.g' || LPAD(l_group_no, 2, '0') || ')' || CHR(10);
            END IF;
            -- utPLSQL 3.2.3 (confirmed against a live instance) silently
            -- drops the ENTIRE package from discovery -- no error, no suite
            -- rows, nothing -- unless a blank line separates the
            -- suite/suitepath block from the first --%test/--%context
            -- annotation. This blank line is therefore load-bearing, not
            -- cosmetic; do not remove it.
            l_spec := l_spec || CHR(10);

            l_body := 'CREATE OR REPLACE PACKAGE BODY ' || l_pkg_name || ' IS' || CHR(10);

            FOR test_no IN 1 .. l_num_tests LOOP
                l_test_name := 'test_' || LPAD(test_no, 2, '0');
                l_key := l_pkg_name || '.' || TO_CHAR(test_no);

                -- OUTCOME axis (0..99): 0-4 pass+output, 5-74 pass, 75-84 fail,
                -- 85-89 error, 90-99 disabled -- i.e. 75% pass / 10% fail / 5%
                -- error / 10% disabled.
                l_outcome := hash_bucket(l_key || '.o', 99, p_seed);
                l_disabled := l_outcome BETWEEN 90 AND 99;

                -- DURATION axis (0..99), independent of outcome: 0-9 slow
                -- (2-10s), 10-19 medium (fixed, short), 20-99 fast (none).
                -- A disabled+slow overlap (~1% of all tests) simply never
                -- executes its sleep, same as any other disabled test.
                l_duration := hash_bucket(l_key || '.d', 99, p_seed);

                IF l_is_context AND test_no = l_num_tests THEN
                    -- Needs a blank line before the --%test it wraps, same as
                    -- the suite/test separator above -- without it utPLSQL
                    -- silently drops the whole --%context block (confirmed
                    -- against a live 3.2.3 instance: the test still compiles
                    -- and runs, but shows up flat under the suite instead of
                    -- nested under a UT_SUITE_CONTEXT).
                    l_spec := l_spec || '  --%context(nested)' || CHR(10) || CHR(10);
                END IF;

                l_spec := l_spec || '  --%test(' || l_test_name || ' ' ||
                    CASE
                        WHEN l_outcome <= 74 THEN 'expected pass'
                        WHEN l_outcome <= 84 THEN 'expected fail'
                        WHEN l_outcome <= 89 THEN 'expected error'
                        ELSE 'expected disabled'
                    END || ')' || CHR(10);
                IF l_disabled THEN
                    l_spec := l_spec || '  --%disabled' || CHR(10);
                END IF;
                l_spec := l_spec || '  PROCEDURE ' || l_test_name || ';' || CHR(10);

                IF l_is_context AND test_no = l_num_tests THEN
                    l_spec := l_spec || CHR(10) || '  --%endcontext' || CHR(10);
                END IF;

                l_body := l_body || '  PROCEDURE ' || l_test_name || ' IS' || CHR(10)
                                  || '  BEGIN' || CHR(10);

                IF NOT l_disabled THEN
                    IF l_duration <= 9 THEN
                        l_slow_secs := 2 + hash_bucket(l_key || '.s', 8, p_seed); -- 2..10
                        l_body := l_body || '    dbms_session.sleep(' || TO_CHAR(l_slow_secs) || ' * ut_perf_gen.scale);' || CHR(10);
                    ELSIF l_duration <= 19 THEN
                        l_med_secs := ROUND(0.05 + hash_bucket(l_key || '.m', 250, p_seed) / 1000, 4); -- 0.05..0.30
                        l_body := l_body || '    dbms_session.sleep(' || TO_CHAR(l_med_secs) || ' * ut_perf_gen.scale);' || CHR(10);
                    END IF;
                END IF;

                l_body := l_body ||
                    CASE
                        WHEN l_outcome <= 4  THEN '    dbms_output.put_line(''ut_perf_gen: ok'');' || CHR(10) || '    ut.expect(1).to_equal(1);' || CHR(10)
                        WHEN l_outcome <= 74 THEN '    ut.expect(1).to_equal(1);' || CHR(10)
                        WHEN l_outcome <= 84 THEN '    ut.expect(1).to_equal(2);' || CHR(10)
                        WHEN l_outcome <= 89 THEN '    raise_application_error(-20000, ''ut_perf_gen: intentional error'');' || CHR(10)
                        ELSE '    ut.expect(1).to_equal(1);' || CHR(10) -- disabled, never runs
                    END;

                l_body := l_body || '  END ' || l_test_name || ';' || CHR(10);
            END LOOP;

            l_spec := l_spec || 'END ' || l_pkg_name || ';';
            l_body := l_body || 'END ' || l_pkg_name || ';';

            EXECUTE IMMEDIATE l_spec;
            EXECUTE IMMEDIATE l_body;
        END LOOP;

        UPDATE ut_perf_config SET packages_generated = p_packages, seed = p_seed, generated_at = SYSTIMESTAMP;
        IF SQL%ROWCOUNT = 0 THEN
            INSERT INTO ut_perf_config (sleep_scale, packages_generated, seed, generated_at)
            VALUES (0, p_packages, p_seed, SYSTIMESTAMP);
        END IF;
        COMMIT;

        -- utPLSQL already parses+caches each package's annotations as it is
        -- compiled above (confirmed against a live 3.2.3 instance: no
        -- explicit action needed for a freshly-compiled package to show up
        -- in get_suites_info()). This call is a best-effort safety net for
        -- that cache, not a requirement -- tolerate it not existing at all
        -- (older utPLSQL) or taking different arguments (its signature is
        -- rebuild_annotation_cache(a_object_owner varchar2, a_object_type
        -- varchar2 := null) as of 3.2.3; it is not part of this extension's
        -- minimum-supported-version contract, so a signature mismatch on
        -- some other version must not fail fixture generation either).
        BEGIN
            EXECUTE IMMEDIATE 'BEGIN ut_runner.rebuild_annotation_cache(a_object_owner => :1); END;' USING USER;
        EXCEPTION
            WHEN OTHERS THEN
                IF SQLCODE NOT IN (-6550, -6553, -4043) THEN -- PLS-00201/PLS-00306/ORA-04043
                    RAISE;
                END IF;
        END;

        SELECT COUNT(*) INTO l_invalid_cnt
          FROM user_objects
         WHERE object_name LIKE 'UT_PERF_TEST\_%' ESCAPE '\'
           AND status != 'VALID';
        IF l_invalid_cnt > 0 THEN
            raise_application_error(-20000, l_invalid_cnt || ' UT_PERF_TEST_* object(s) are INVALID after generate() -- check user_errors.');
        END IF;
    END generate;

    PROCEDURE drop_all IS
    BEGIN
        FOR pkg IN (SELECT object_name FROM user_objects
                     WHERE object_name LIKE 'UT_PERF_TEST\_%' ESCAPE '\'
                       AND object_type = 'PACKAGE')
        LOOP
            EXECUTE IMMEDIATE 'DROP PACKAGE ' || pkg.object_name;
        END LOOP;
    END drop_all;

END ut_perf_gen;
/
